### ISSUE TITLE
How to compute the normalized scores for DMC tasks?

### ISSUE THREAD

**Issue by younggyoseo** [facebookresearch/eai-vc#14] opened 2023-07-03 03:18 UTC
Hi, thanks for releasing the nice benchmark. Could you share the details on how the DMC scores are normalized to [0, 100] scale in the paper? I might be missing something but I couldn't find the corresponding details in this paper or also in the previous PVR paper. Thanks in advance!

**Comment by godnpeter** [comment] 2023-09-23 10:47
I am also curious about this. Are we suppose to just divide the final agent's performance score with 1000, which is the max score an agent can achieve in DMC, or are we suppose to normalize the final agent's performance score with the expert demonstration's average score?

**Comment by yangjiangeyjg** [comment] 2023-10-02 09:24
> I am also curious about this. Are we suppose to just divide the final agent's performance score with 1000, which is the max score an agent can achieve in DMC, or are we suppose to normalize the final agent's performance score with the expert demonstration's average score?

The same doubts. +1

**Comment by xwen99** [comment] 2024-04-19 09:23
From my reimplementation, it seems the scores are first normalized by expert demonstrations' scores per task (smaller than 1000), and then averaged.
|     task     	| expert score 	|
|:------------:	|:------------:	|
| walker_stand 	|    971.22    	|
|  walker_walk 	|    918.07    	|
| reacher_easy 	|    963.04    	|
|  cheetah_run 	|    759.17    	|
|  finger_spin 	|    743.33    	|

**Comment by aravindr93** [comment] 2024-05-03 02:32
The results reported in the paper are normalized by 1000 (max score) and not demo score. I am closing this issue since the original question was answered. @xwen99  if the reproducibility issue persists, please open a separate issue for a deeper dive specifically on that topic.

**Closed as completed by aravindr93** 2024-05-03 02:32 UTC
